"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { AutomationHistory as History } from "@/lib/types";
import { CodeBlock } from "@/components/code-block";
import { StatusBadge } from "@/components/status-badge";

export function AutomationHistory({ history, expectedHash }: { history: History; expectedHash: string }) {
  const router = useRouter(); const [reviewer, setReviewer] = useState(""); const [comment, setComment] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const review = (id: number, decision: "APPROVED" | "REJECTED") => { if (!reviewer.trim()) { setError("Reviewer name is required."); return; } startTransition(async () => { const response = await fetch(`/api/backend/api/automation-artifacts/${id}/review`, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify({ decision, reviewer_name: reviewer.trim(), comment: comment.trim() }) }); const payload = (await response.json().catch(() => ({}))) as { error?: string }; if (!response.ok) setError(payload.error ?? "Review failed."); else router.refresh(); }); };
  return <section className="document-preview-section panel"><div className="panel-header"><div><h2>Automation</h2><p>Technical implementation versions are separate from the immutable business specification.</p></div><span className="section-counter">{history.artifacts.length}</span></div><p><strong>Locked expected hash:</strong> <span className="mono">{expectedHash}</span></p>{history.artifacts.map((artifact, index) => <article className="candidate-card" key={artifact.id}><header className="candidate-header"><div><strong>{artifact.file_path} · v{artifact.version_number}</strong><p>{artifact.framework} · technical context <span className="mono">{artifact.technical_context_hash.slice(0, 12)}…</span></p></div><StatusBadge status={artifact.status} /></header><div className="candidate-body"><p><strong>Setup:</strong> {artifact.setup || "—"}</p><p><strong>Assertions:</strong> {artifact.assertions.join(" · ")}</p><CodeBlock title="Generated Go unit test" code={artifact.source} label="GO" />{history.artifacts[index + 1] ? <details><summary>Compare with previous artifact version</summary><div className="repair-codes"><CodeBlock title={`Previous v${history.artifacts[index + 1].version_number}`} code={history.artifacts[index + 1].source} label="GO" compact /><CodeBlock title={`Current v${artifact.version_number}`} code={artifact.source} label="GO" compact /></div></details> : null}<details><summary>Technical context (not business evidence)</summary>{artifact.technical_context.map((chunk) => <pre key={chunk.id || chunk.chunk_key}>{chunk.file_path}\n{chunk.content}</pre>)}</details>{artifact.status === "DRAFT" ? <div className="bulk-review-bar"><label><span>Reviewer</span><input value={reviewer} onChange={(event) => setReviewer(event.target.value)} /></label><label><span>Comment</span><input value={comment} onChange={(event) => setComment(event.target.value)} /></label><button className="button secondary" disabled={pending} onClick={() => review(artifact.id, "REJECTED")}>Reject</button><button className="button" disabled={pending} onClick={() => review(artifact.id, "APPROVED")}>Approve</button></div> : null}</div></article>)}{!history.artifacts.length ? <p className="table-subtitle">No automation artifact has been generated. The test case remains manual.</p> : null}{error ? <p className="form-error">{error}</p> : null}</section>;
}
