"use client";

import { useState, useTransition } from "react";
import type { BusinessTestCase, TestExport } from "@/lib/types";
import { formatDate } from "@/lib/presentation";

export function ExportControls({ setId, suiteId, exports, testCases }: { setId: number; suiteId: number; exports: TestExport[]; testCases: BusinessTestCase[] }) {
  const [format, setFormat] = useState<"XLSX" | "MARKDOWN">("XLSX");
  const [generatedBy, setGeneratedBy] = useState("");
  const [error, setError] = useState("");
	const [status, setStatus] = useState("ALL");
	const [risk, setRisk] = useState("ALL");
	const [sortBy, setSortBy] = useState("KEY");
  const [pending, startTransition] = useTransition();
  const createExport = () => {
    setError("");
    if (!generatedBy.trim()) { setError("Enter the QA/reviewer name for export provenance."); return; }
	const testCaseIds = testCases.filter((item) => (status === "ALL" || item.status === status) && (risk === "ALL" || item.risk === risk)).map((item) => item.id);
	if (!testCaseIds.length) { setError("The selected export filters contain no test cases."); return; }
    startTransition(async () => {
      const response = await fetch(`/api/backend/api/document-sets/${setId}/exports`, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify({ test_suite_id: suiteId, format, generated_by: generatedBy.trim(), test_case_ids: testCaseIds, sort_by: sortBy }) });
      const payload = (await response.json().catch(() => ({}))) as TestExport & { error?: string };
      if (!response.ok) { setError(payload.error ?? "Export failed."); return; }
      window.location.assign(`/api/backend${payload.download_url}`);
    });
  };
  return <section className="panel">
    <div className="panel-header"><div><h2>Immutable execution export</h2><p>XLSX includes Test Cases, Run History, Summary and Metadata. Every export keeps its own snapshot and SHA-256.</p></div></div>
    <div className="bulk-review-bar"><label><span>Format</span><select value={format} onChange={(event) => setFormat(event.target.value as "XLSX" | "MARKDOWN")}><option>XLSX</option><option>MARKDOWN</option></select></label><label><span>Review status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option>ALL</option><option>DRAFT</option><option>APPROVED</option><option>REJECTED</option></select></label><label><span>Risk</span><select value={risk} onChange={(event) => setRisk(event.target.value)}><option>ALL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><label><span>Sort</span><select value={sortBy} onChange={(event) => setSortBy(event.target.value)}><option value="KEY">Case ID</option><option value="TITLE">Title</option><option value="RISK">Risk</option></select></label><label><span>Generated by</span><input value={generatedBy} onChange={(event) => setGeneratedBy(event.target.value)} placeholder="QA / Test Lead" /></label><button className="button" disabled={pending || suiteId <= 0} onClick={createExport}>{pending ? "Preparing…" : `Download ${format}`}</button></div>
    {error ? <p className="form-error panel-message">{error}</p> : null}
    {exports.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Artifact</th><th>Rows</th><th>Generated</th><th>Snapshot</th></tr></thead><tbody>{exports.slice(0, 10).map((item) => <tr key={item.id}><td><a href={`/api/backend${item.download_url}`}><span className="table-title">{item.filename}</span><span className="table-subtitle">{item.format} · by {item.generated_by}</span></a></td><td>{item.row_count}</td><td>{formatDate(item.created_at)}</td><td className="mono">{item.snapshot_hash.slice(0, 12)}…</td></tr>)}</tbody></table></div> : <p className="table-subtitle">No export snapshot has been created yet.</p>}
  </section>;
}
