"use client";

import { useEffect, useState, useTransition } from "react";
import type { BusinessTestCase, SuiteRelease, TestExport } from "@/lib/types";
import { formatDate } from "@/lib/presentation";

type Props = {
  setId: number;
  suiteId: number;
  exports: TestExport[];
  testCases: BusinessTestCase[];
  releases: SuiteRelease[];
};

export function ExportControls({ setId, suiteId, exports, testCases, releases: initialReleases }: Props) {
  const [releases, setReleases] = useState(initialReleases);
  useEffect(() => {
    const abort = new AbortController();
    const reload = async () => {
      try {
        const response = await fetch(`/api/backend/api/document-sets/${setId}/suite-releases`, {signal:abort.signal, cache:"no-store"});
        if (response.ok) setReleases((await response.json()).releases);
      } catch { /* Keep prior release choices; retry after next publication. */ }
    };
    window.addEventListener("document-workspace-updated", reload);
    return () => { abort.abort(); window.removeEventListener("document-workspace-updated", reload); };
  }, [setId]);
  const [format, setFormat] = useState<"XLSX" | "MARKDOWN">("XLSX");
  const [generatedBy, setGeneratedBy] = useState("");
  const [error, setError] = useState("");
  const [source, setSource] = useState("WORKING");
  const [status, setStatus] = useState("ALL");
  const [risk, setRisk] = useState("ALL");
  const [sortBy, setSortBy] = useState("KEY");
  const [pending, startTransition] = useTransition();
  const selectedRelease = releases.find((item) => String(item.id) === source);
  const workingIDs = testCases
    .filter((item) => (status === "ALL" || item.status === status) && (risk === "ALL" || item.risk === risk))
    .map((item) => item.id);
  const exportCount = selectedRelease ? selectedRelease.items.length : workingIDs.length;

  const createExport = () => {
    setError("");
    if (!generatedBy.trim()) {
      setError("Enter the QA/reviewer name for export provenance.");
      return;
    }
    if (!exportCount) {
      setError("The selected export contains no test cases.");
      return;
    }
    startTransition(async () => {
      const response = await fetch(`/api/backend/api/document-sets/${setId}/exports`, {
        method: "POST",
        headers: { Accept: "application/json", "Content-Type": "application/json" },
        body: JSON.stringify({
          test_suite_id: selectedRelease?.test_suite_id ?? suiteId,
          suite_release_id: selectedRelease?.id,
          format,
          generated_by: generatedBy.trim(),
          test_case_ids: selectedRelease ? undefined : workingIDs,
          sort_by: sortBy,
        }),
      });
      const payload = (await response.json().catch(() => ({}))) as TestExport & { error?: string };
      if (!response.ok) {
        setError(payload.error ?? "Export failed.");
        return;
      }
      window.location.assign(`/api/backend${payload.download_url}`);
    });
  };

  return <section className="panel">
    <div className="panel-header"><div><h2>Immutable testcase export</h2><p>Choose the working heads or one published release. The resulting artifact keeps its exact revisions, source versions and SHA-256.</p></div></div>
    <div className="bulk-review-bar">
      <label><span>Export source</span><select value={source} onChange={(event) => setSource(event.target.value)}>
        <option value="WORKING">Working set ({testCases.length} latest revisions)</option>
        {releases.map((release) => <option key={release.id} value={release.id}>
          Published R{release.release_number} ({release.items.length} revisions)
        </option>)}
      </select></label>
      <label><span>Format</span><select value={format} onChange={(event) => setFormat(event.target.value as "XLSX" | "MARKDOWN")}><option>XLSX</option><option>MARKDOWN</option></select></label>
      <label><span>Review status</span><select value={status} disabled={Boolean(selectedRelease)} onChange={(event) => setStatus(event.target.value)}><option>ALL</option><option>DRAFT</option><option>APPROVED</option><option>REJECTED</option></select></label>
      <label><span>Risk</span><select value={risk} disabled={Boolean(selectedRelease)} onChange={(event) => setRisk(event.target.value)}><option>ALL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label>
      <label><span>Sort</span><select value={sortBy} onChange={(event) => setSortBy(event.target.value)}><option value="KEY">Case ID</option><option value="TITLE">Title</option><option value="RISK">Risk</option></select></label>
      <label><span>Generated by</span><input value={generatedBy} onChange={(event) => setGeneratedBy(event.target.value)} placeholder="QA / Test Lead" /></label>
      <button className="button" disabled={pending || suiteId <= 0} onClick={createExport}>{pending ? "Preparing…" : `Download ${format} · ${exportCount} cases`}</button>
    </div>
    {selectedRelease ? <p className="notice"><strong>Published R{selectedRelease.release_number}</strong> This export uses manifest <span className="mono">{selectedRelease.manifest_hash.slice(0, 12)}…</span>; working filters do not change it.</p> : <p className="table-subtitle">Working-set filters select {exportCount} current head revisions. They do not change a published release.</p>}
    {error ? <p className="form-error panel-message">{error}</p> : null}
    {exports.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Artifact</th><th>Source</th><th>Rows</th><th>Generated</th><th>Snapshot</th></tr></thead><tbody>{exports.slice(0, 10).map((item) => <tr key={item.id}><td><a href={`/api/backend${item.download_url}`}><span className="table-title">{item.filename}</span><span className="table-subtitle">{item.format} · by {item.generated_by}</span></a></td><td>{item.test_run_id ? `Run #${item.test_run_id}` : item.suite_release_id ? `Release #${item.suite_release_id}` : "Working set"}</td><td>{item.row_count}</td><td>{formatDate(item.created_at)}</td><td className="mono">{item.snapshot_hash.slice(0, 12)}…</td></tr>)}</tbody></table></div> : <p className="table-subtitle">No export snapshot has been created yet.</p>}
  </section>;
}
