"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { AnalysisTestScope } from "@/lib/types";
import { StatusBadge } from "@/components/status-badge";

export function TestScopeWorkspace({ scope }: { scope: AnalysisTestScope }) {
  const router = useRouter(); const [reviewer, setReviewer] = useState(""); const [comment, setComment] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const decide = (testCaseId: number, included: boolean) => { if (!reviewer.trim() || !comment.trim()) { setError("Reviewer and audit comment are required."); return; } setError(""); startTransition(async () => { const response = await fetch(`/api/backend/api/analyses/${scope.analysis_job_id}/test-scope`, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify({ test_case_id: testCaseId, included, reviewer_name: reviewer.trim(), comment: comment.trim() }) }); const payload = (await response.json().catch(() => ({}))) as { error?: string }; if (!response.ok) { setError(payload.error ?? "Scope update failed."); return; } router.refresh(); }); };
  const generate = (testCaseId: number) => startTransition(async () => { const response = await fetch(`/api/backend/api/analyses/${scope.analysis_job_id}/automation/generate`, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify({ test_case_id: testCaseId }) }); const payload = (await response.json().catch(() => ({}))) as { error?: string; message?: string }; if (!response.ok) setError(payload.error ?? "Automation generation failed."); else if (payload.message) setError(payload.message); else router.refresh(); });
  return <section className="panel"><div className="panel-header"><div><h2>Document-grounded execution scope</h2><p>Release #{scope.suite_release_id} · baseline <span className="mono">{scope.baseline_hash.slice(0, 12)}…</span> · confidence {Math.round(scope.mapping_confidence * 100)}% · run #{scope.test_run_id}</p></div><StatusBadge status={scope.selection_mode} /></div>{scope.warning ? <p className="notice"><strong>Safe fallback</strong>{scope.warning}</p> : null}{scope.signals.length ? <details><summary>Technical path/module/symbol signals ({scope.signals.length})</summary><div className="evidence-list">{scope.signals.map((signal) => <p key={signal.id}><StatusBadge status={signal.signal_type} /> <span className="mono">{signal.signal_value}</span> · {Math.round(signal.confidence * 100)}%<span className="table-subtitle">{signal.explanation}</span></p>)}</div></details> : null}<div className="bulk-review-bar"><label><span>Reviewer</span><input value={reviewer} onChange={(event) => setReviewer(event.target.value)} /></label><label><span>Audit comment</span><input value={comment} onChange={(event) => setComment(event.target.value)} /></label></div>{error ? <p className="form-error panel-message">{error}</p> : null}<div className="table-wrap"><table className="data-table"><thead><tr><th>Run</th><th>Business test case</th><th>Reason</th><th>Confidence</th><th>Automation</th></tr></thead><tbody>{scope.items.map((item) => <tr key={item.id}><td><input type="checkbox" checked={item.included} disabled={pending} onChange={(event) => decide(item.test_case_id, event.target.checked)} aria-label={`Include ${item.test_case_key}`} /></td><td><Link href={`/documents/${scope.document_set_id}/test-cases/${item.test_case_id}`}><span className="table-title">{item.test_case_key} · {item.title}</span><span className="table-subtitle">{item.expected_result}</span></Link></td><td><StatusBadge status={item.selection_reason} /><span className="table-subtitle">{item.explanation}</span></td><td>{Math.round(item.confidence * 100)}%</td><td><StatusBadge status={item.automation_status} />{item.included && item.automation_status !== "AUTOMATED" ? <button className="button secondary" disabled={pending} onClick={() => generate(item.test_case_id)}>Generate Go test</button> : null}</td></tr>)}</tbody></table></div></section>;
}
