DROP TRIGGER IF EXISTS test_run_items_immutable_expected ON test_run_items;
DROP FUNCTION IF EXISTS prevent_test_run_expected_update();
DROP TRIGGER IF EXISTS automation_artifacts_business_contract ON automation_artifacts;
DROP FUNCTION IF EXISTS validate_automation_artifact_business_contract();
DROP TRIGGER IF EXISTS document_versions_immutable_identity ON document_versions;
DROP FUNCTION IF EXISTS prevent_document_version_identity_update();
DROP TRIGGER IF EXISTS requirement_evidence_immutable ON requirement_evidence;
DROP TRIGGER IF EXISTS document_blocks_immutable ON document_blocks;
DROP FUNCTION IF EXISTS prevent_source_evidence_update();
DROP TABLE IF EXISTS test_run_evidence;
DROP TABLE IF EXISTS test_run_items;
DROP TABLE IF EXISTS test_runs;
DROP TABLE IF EXISTS automation_artifacts;
DROP TABLE IF EXISTS test_case_reviews;
DROP TABLE IF EXISTS test_case_requirement_links;
DROP TABLE IF EXISTS test_case_steps;
DROP TABLE IF EXISTS test_cases;
DROP TABLE IF EXISTS test_suites;
DROP TABLE IF EXISTS requirement_reviews;
DROP TABLE IF EXISTS open_questions;
DROP TABLE IF EXISTS requirement_conflicts;
DROP TABLE IF EXISTS requirement_evidence;
DROP TABLE IF EXISTS requirements;
DROP TABLE IF EXISTS document_chunks;
DROP TABLE IF EXISTS document_blocks;
DROP TABLE IF EXISTS document_versions;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS document_sets;
