package evidence

import (
	"archive/zip"
	"bytes"
	"encoding/xml"
	"fmt"
	"io"
	"path"
	"strings"

	"github.com/maccuatruong/ai-test-assistant/backend/internal/report"
)

const relationshipNamespace = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
const maxXLSXPartBytes = 16 << 20
const maxXLSXBytes = 64 << 20

// Verify only the repository's generated inline-string XLSX format. This is not
// an arbitrary workbook importer, a formula evaluator, or proof of execution.
// Read in memory with bounds; never extract ZIP paths or fetch relationships.
func validateWorkbook(content []byte, snapshot report.Snapshot) bool {
	if len(content) > maxXLSXBytes {
		return false
	}
	archive, err := zip.NewReader(bytes.NewReader(content), int64(len(content)))
	if err != nil || len(archive.File) > 32 {
		return false
	}
	parts := make(map[string][]byte, len(archive.File))
	var total uint64
	for _, file := range archive.File {
		if _, duplicate := parts[file.Name]; duplicate || path.Clean(file.Name) != file.Name || strings.HasPrefix(file.Name, "/") || strings.HasPrefix(file.Name, "../") || strings.Contains(file.Name, "\\") || file.UncompressedSize64 > maxXLSXPartBytes {
			return false
		}
		total += file.UncompressedSize64
		if total > maxXLSXBytes {
			return false
		}
		reader, err := file.Open()
		if err != nil {
			return false
		}
		data, err := io.ReadAll(io.LimitReader(reader, maxXLSXPartBytes+1))
		_ = reader.Close()
		if err != nil || len(data) > maxXLSXPartBytes || uint64(len(data)) != file.UncompressedSize64 {
			return false
		}
		parts[file.Name] = data
	}
	var workbook struct {
		XMLName xml.Name `xml:"http://schemas.openxmlformats.org/spreadsheetml/2006/main workbook"`
		Sheets  []struct {
			Name  string `xml:"name,attr"`
			ID    string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr"`
			State string `xml:"state,attr"`
		} `xml:"sheets>sheet"`
	}
	if !decodeWorkbookXML(parts["xl/workbook.xml"], &workbook) || len(workbook.Sheets) != 4 {
		return false
	}
	root, ok := workbookRelationships(parts["_rels/.rels"])
	if !ok {
		return false
	}
	mainCount := 0
	for _, rel := range root {
		if rel.Type == relationshipNamespace+"/officeDocument" {
			mainCount++
			if rel.Target != "xl/workbook.xml" {
				return false
			}
		}
	}
	if mainCount != 1 {
		return false
	}
	rels, ok := workbookRelationships(parts["xl/_rels/workbook.xml.rels"])
	if !ok {
		return false
	}
	for i, name := range []string{"Test Cases", "Run History", "Summary", "Metadata"} {
		sheet := workbook.Sheets[i]
		rel, exists := rels[sheet.ID]
		if !exists || sheet.Name != name || (sheet.State != "" && sheet.State != "visible") || rel.Type != relationshipNamespace+"/worksheet" || rel.Target != fmt.Sprintf("worksheets/sheet%d.xml", i+1) {
			return false
		}
	}

	cases := [][]string{{"TC ID", "Requirement Trace", "Objective", "Preconditions", "Steps", "Test Data", "Role", "Expected Result", "Priority", "Environment", "Actual Result", "Status", "Evidence", "Notes", "Automation Status", "Source Status"}}
	for _, row := range snapshot.Rows {
		cases = append(cases, []string{row.TestCaseKey, row.RequirementTrace, row.Objective, row.Preconditions, strings.Join(row.Steps, "\n"), row.TestData, row.Role, row.ExpectedResult, row.Priority, row.Environment, row.ActualResult, row.Status, strings.Join(row.Evidence, "\n"), row.Notes, row.AutomationStatus, row.SourceStatus})
	}
	history := [][]string{{"TC ID", "Run", "Attempt", "Source SHA", "Environment", "Actual Result", "Status", "Evidence", "Time"}}
	for _, row := range snapshot.RunHistory {
		history = append(history, []string{row.TestCaseKey, fmt.Sprint(row.RunID), fmt.Sprint(row.Attempt), row.SourceSHA, row.Environment, row.ActualResult, row.Status, strings.Join(row.Evidence, "\n"), row.CreatedAt.Format("2006-01-02 15:04:05Z07:00")})
	}
	metadata := [][]string{{"Key", "Value"}, {"Document set", snapshot.DocumentSetName}, {"Product", snapshot.ProductName}, {"Scope", snapshot.Scope}, {"Test suite", snapshot.TestSuiteName}, {"Generated at", snapshot.GeneratedAt.Format("2006-01-02 15:04:05Z07:00")}, {"Generated by", snapshot.GeneratedBy}, {"Reviewer", snapshot.Reviewer}}
	if snapshot.SuiteReleaseID != nil {
		metadata = append(metadata, []string{"Suite release", fmt.Sprintf("%s | R%d | ID %d", snapshot.ReleaseName, snapshot.ReleaseNumber, *snapshot.SuiteReleaseID)}, []string{"Release manifest hash", snapshot.ReleaseManifestHash})
	}
	for _, version := range snapshot.DocumentVersions {
		metadata = append(metadata, []string{"Document version", fmt.Sprintf("%s v%d | %s | %s", version.DocumentName, version.VersionNumber, version.ApprovalStatus, version.SHA256)})
	}
	for _, revision := range snapshot.RevisionManifest {
		metadata = append(metadata, []string{"Testcase revision", fmt.Sprintf("%s v%d | row %d | family %d | %s", revision.TestCaseKey, revision.RevisionNumber, revision.TestCaseID, revision.FamilyID, revision.ContentHash)})
	}
	last := max(len(snapshot.Rows)+1, 2)
	summary := [][]string{{"Metric", "Value"}, {"Total", "0"}, {"Passed", "0"}, {"Failed", "0"}, {"Not run", "0"}}
	formulas := map[string]string{
		"B2": fmt.Sprintf("COUNTA('Test Cases'!A2:A%d)", last),
		"B3": fmt.Sprintf(`COUNTIF('Test Cases'!L2:L%d,"P")`, last),
		"B4": fmt.Sprintf(`COUNTIF('Test Cases'!L2:L%d,"F")`, last),
		"B5": fmt.Sprintf(`COUNTIF('Test Cases'!L2:L%d,"NY")`, last),
	}
	return verifySheetCells(parts["xl/worksheets/sheet1.xml"], cases, nil) &&
		verifySheetCells(parts["xl/worksheets/sheet2.xml"], history, nil) &&
		verifySheetCells(parts["xl/worksheets/sheet3.xml"], summary, formulas) &&
		verifySheetCells(parts["xl/worksheets/sheet4.xml"], metadata, nil)
}

type workbookRelationship struct {
	ID     string `xml:"Id,attr"`
	Type   string `xml:"Type,attr"`
	Target string `xml:"Target,attr"`
	Mode   string `xml:"TargetMode,attr"`
}

func workbookRelationships(data []byte) (map[string]workbookRelationship, bool) {
	var document struct {
		XMLName xml.Name               `xml:"http://schemas.openxmlformats.org/package/2006/relationships Relationships"`
		Items   []workbookRelationship `xml:"Relationship"`
	}
	if !decodeWorkbookXML(data, &document) {
		return nil, false
	}
	result := map[string]workbookRelationship{}
	for _, item := range document.Items {
		if _, duplicate := result[item.ID]; duplicate || item.ID == "" || item.Mode != "" {
			return nil, false
		}
		result[item.ID] = item
	}
	return result, true
}

func verifySheetCells(data []byte, expected [][]string, formulas map[string]string) bool {
	var sheet struct {
		XMLName xml.Name `xml:"http://schemas.openxmlformats.org/spreadsheetml/2006/main worksheet"`
		Data    []struct {
			Rows []struct {
				Index  int    `xml:"r,attr"`
				Hidden string `xml:"hidden,attr"`
				Cells  []struct {
					Ref     string   `xml:"r,attr"`
					Type    string   `xml:"t,attr"`
					Formula []string `xml:"f"`
					Value   []string `xml:"v"`
					Inline  []struct {
						Text []string `xml:"t"`
					} `xml:"is"`
				} `xml:"c"`
			} `xml:"row"`
		} `xml:"sheetData"`
	}
	if !decodeWorkbookXML(data, &sheet) || len(sheet.Data) != 1 || len(sheet.Data[0].Rows) != len(expected) {
		return false
	}
	for i, row := range sheet.Data[0].Rows {
		if row.Index != i+1 || row.Hidden != "" || len(row.Cells) != len(expected[i]) {
			return false
		}
		for j, cell := range row.Cells {
			if cell.Ref != fmt.Sprintf("%c%d", 'A'+j, i+1) {
				return false
			}
			if formula, exists := formulas[cell.Ref]; exists {
				if cell.Type != "" || len(cell.Inline) != 0 || len(cell.Formula) != 1 || cell.Formula[0] != formula || len(cell.Value) != 1 || cell.Value[0] != expected[i][j] {
					return false
				}
				continue
			}
			if cell.Type != "inlineStr" || len(cell.Formula) != 0 || len(cell.Value) != 0 || len(cell.Inline) != 1 || len(cell.Inline[0].Text) != 1 || cell.Inline[0].Text[0] != workbookCellText(expected[i][j]) {
				return false
			}
		}
	}
	return true
}

// encoding/xml.Unmarshal alone stops at the first root element. Validate the
// entire document first, including namespace, duplicate attributes and depth.
func decodeWorkbookXML(data []byte, target any) bool {
	decoder := xml.NewDecoder(bytes.NewReader(data))
	depth, roots := 0, 0
	namespace := ""
	for {
		token, err := decoder.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return false
		}
		switch item := token.(type) {
		case xml.StartElement:
			if depth == 0 {
				roots++
				namespace = item.Name.Space
			}
			depth++
			if roots != 1 || depth > 32 || item.Name.Space != namespace {
				return false
			}
			attributes := map[xml.Name]bool{}
			for _, attribute := range item.Attr {
				if attributes[attribute.Name] {
					return false
				}
				attributes[attribute.Name] = true
			}
		case xml.EndElement:
			depth--
		case xml.CharData:
			if depth == 0 && strings.TrimSpace(string(item)) != "" {
				return false
			}
		case xml.Directive:
			return false
		}
	}
	return roots == 1 && depth == 0 && xml.Unmarshal(data, target) == nil
}

// Independent implementation of the exported-cell contract: XML-safe Unicode,
// 32767-rune truncation, then formula-prefix escaping. The full text stays in
// the immutable snapshot; Excel cells alone cannot prove untruncated content.
func workbookCellText(value string) string {
	clean := make([]rune, 0, min(len(value), 32767))
	for _, r := range strings.ToValidUTF8(value, "�") {
		if r == '\t' || r == '\n' || r == '\r' || r >= 0x20 && r <= 0xD7FF || r >= 0xE000 && r <= 0xFFFD || r >= 0x10000 && r <= 0x10FFFF {
			clean = append(clean, r)
			if len(clean) == 32767 {
				break
			}
		}
	}
	value = string(clean)
	trimmed := strings.TrimLeft(value, " \t\r\n")
	if trimmed != "" && strings.ContainsRune("=+-@", rune(trimmed[0])) {
		return "'" + value
	}
	return value
}
