package report

import (
	"archive/zip"
	"bytes"
	"encoding/xml"
	"fmt"
	"sort"
	"strings"
	"unicode/utf8"
)

const maxExcelCellRunes = 32767

var testCaseHeaders = []string{
	"TC ID", "Requirement Trace", "Objective", "Preconditions", "Steps", "Test Data",
	"Role", "Expected Result", "Priority", "Environment", "Actual Result", "Status",
	"Evidence", "Notes", "Automation Status", "Source Status",
}

func RenderMarkdown(snapshot Snapshot) []byte {
	var output strings.Builder
	fmt.Fprintf(&output, "# Test Execution — %s\n\n", markdownText(snapshot.TestSuiteName))
	fmt.Fprintf(&output, "- Document set: %s\n- Product: %s\n- Scope: %s\n", markdownText(snapshot.DocumentSetName), markdownText(snapshot.ProductName), markdownText(snapshot.Scope))
	if snapshot.SuiteReleaseID != nil {
		fmt.Fprintf(&output, "- Suite release: %s (R%d, ID %d)\n- Release manifest: %s\n",
			markdownText(snapshot.ReleaseName), snapshot.ReleaseNumber, *snapshot.SuiteReleaseID,
			markdownText(snapshot.ReleaseManifestHash))
	}
	fmt.Fprintf(&output, "- Generated at: %s\n- Generated by: %s\n- Reviewer: %s\n\n", snapshot.GeneratedAt.Format("2006-01-02 15:04:05Z07:00"), markdownText(snapshot.GeneratedBy), markdownText(snapshot.Reviewer))
	output.WriteString("## Document versions\n\n| Document | Version | SHA-256 | Approval |\n|---|---:|---|---|\n")
	for _, version := range snapshot.DocumentVersions {
		fmt.Fprintf(&output, "| %s | %d | %s | %s |\n", markdownText(version.DocumentName), version.VersionNumber, markdownText(version.SHA256), markdownText(version.ApprovalStatus))
	}
	output.WriteString("\n## Test cases\n\n|")
	for _, header := range testCaseHeaders {
		fmt.Fprintf(&output, " %s |", header)
	}
	output.WriteString("\n|")
	for range testCaseHeaders {
		output.WriteString("---|")
	}
	output.WriteByte('\n')
	for _, row := range snapshot.Rows {
		values := rowValues(row)
		output.WriteByte('|')
		for _, value := range values {
			fmt.Fprintf(&output, " %s |", markdownText(value))
		}
		output.WriteByte('\n')
	}
	output.WriteString("\n## Run history\n\n| TC ID | Run | Attempt | Source SHA | Environment | Actual Result | Status | Evidence | Time |\n|---|---:|---:|---|---|---|---|---|---|\n")
	for _, row := range snapshot.RunHistory {
		fmt.Fprintf(&output, "| %s | %d | %d | %s | %s | %s | %s | %s | %s |\n",
			markdownText(row.TestCaseKey), row.RunID, row.Attempt, markdownText(row.SourceSHA),
			markdownText(row.Environment), markdownText(row.ActualResult), markdownText(row.Status),
			markdownText(strings.Join(row.Evidence, "\n")), row.CreatedAt.Format("2006-01-02 15:04:05Z07:00"))
	}
	return []byte(output.String())
}

func RenderXLSX(snapshot Snapshot) ([]byte, error) {
	var output bytes.Buffer
	archive := zip.NewWriter(&output)
	files := map[string]string{
		"[Content_Types].xml":        contentTypesXML,
		"_rels/.rels":                rootRelationshipsXML,
		"xl/workbook.xml":            workbookXML,
		"xl/_rels/workbook.xml.rels": workbookRelationshipsXML,
		"xl/styles.xml":              stylesXML,
		"docProps/core.xml":          fmt.Sprintf(corePropertiesXML, xmlEscape(snapshot.GeneratedBy), snapshot.GeneratedAt.Format("2006-01-02T15:04:05Z")),
		"docProps/app.xml":           appPropertiesXML,
		"xl/worksheets/sheet1.xml":   renderSheet(testCaseHeaders, testCaseRows(snapshot.Rows), nil),
		"xl/worksheets/sheet2.xml":   renderSheet([]string{"TC ID", "Run", "Attempt", "Source SHA", "Environment", "Actual Result", "Status", "Evidence", "Time"}, historyRows(snapshot.RunHistory), nil),
		"xl/worksheets/sheet3.xml":   renderSheet([]string{"Metric", "Value"}, nil, summaryFormulas(len(snapshot.Rows))),
		"xl/worksheets/sheet4.xml":   renderSheet([]string{"Key", "Value"}, metadataRows(snapshot), nil),
	}
	order := make([]string, 0, len(files))
	for name := range files {
		order = append(order, name)
	}
	sort.Strings(order)
	for _, name := range order {
		writer, err := archive.Create(name)
		if err != nil {
			return nil, fmt.Errorf("create xlsx part %s: %w", name, err)
		}
		if _, err := writer.Write([]byte(files[name])); err != nil {
			return nil, fmt.Errorf("write xlsx part %s: %w", name, err)
		}
	}
	if err := archive.Close(); err != nil {
		return nil, fmt.Errorf("close xlsx: %w", err)
	}
	return output.Bytes(), nil
}

func rowValues(row ExecutionRow) []string {
	return []string{row.TestCaseKey, row.RequirementTrace, row.Objective, row.Preconditions,
		strings.Join(row.Steps, "\n"), row.TestData, row.Role, row.ExpectedResult, row.Priority,
		row.Environment, row.ActualResult, row.Status, strings.Join(row.Evidence, "\n"), row.Notes,
		row.AutomationStatus, row.SourceStatus}
}

func testCaseRows(rows []ExecutionRow) [][]string {
	result := make([][]string, 0, len(rows))
	for _, row := range rows {
		result = append(result, rowValues(row))
	}
	return result
}

func historyRows(rows []RunHistoryRow) [][]string {
	result := make([][]string, 0, len(rows))
	for _, row := range rows {
		result = append(result, []string{row.TestCaseKey, fmt.Sprint(row.RunID), fmt.Sprint(row.Attempt),
			row.SourceSHA, row.Environment, row.ActualResult, row.Status, strings.Join(row.Evidence, "\n"),
			row.CreatedAt.Format("2006-01-02 15:04:05Z07:00")})
	}
	return result
}

func metadataRows(snapshot Snapshot) [][]string {
	rows := [][]string{{"Document set", snapshot.DocumentSetName}, {"Product", snapshot.ProductName},
		{"Scope", snapshot.Scope}, {"Test suite", snapshot.TestSuiteName},
		{"Generated at", snapshot.GeneratedAt.Format("2006-01-02 15:04:05Z07:00")},
		{"Generated by", snapshot.GeneratedBy}, {"Reviewer", snapshot.Reviewer}}
	if snapshot.SuiteReleaseID != nil {
		rows = append(rows, []string{"Suite release", fmt.Sprintf("%s | R%d | ID %d",
			snapshot.ReleaseName, snapshot.ReleaseNumber, *snapshot.SuiteReleaseID)},
			[]string{"Release manifest hash", snapshot.ReleaseManifestHash})
	}
	for _, version := range snapshot.DocumentVersions {
		rows = append(rows, []string{"Document version", fmt.Sprintf("%s v%d | %s | %s", version.DocumentName, version.VersionNumber, version.ApprovalStatus, version.SHA256)})
	}
	for _, revision := range snapshot.RevisionManifest {
		rows = append(rows, []string{"Testcase revision", fmt.Sprintf("%s v%d | row %d | family %d | %s",
			revision.TestCaseKey, revision.RevisionNumber, revision.TestCaseID,
			revision.FamilyID, revision.ContentHash)})
	}
	return rows
}

func summaryFormulas(rowCount int) [][]formulaCell {
	last := rowCount + 1
	if last < 2 {
		last = 2
	}
	rangeRef := fmt.Sprintf("'Test Cases'!L2:L%d", last)
	return [][]formulaCell{
		{{Value: "Total", Formula: fmt.Sprintf("COUNTA('Test Cases'!A2:A%d)", last)}},
		{{Value: "Passed", Formula: fmt.Sprintf(`COUNTIF(%s,"P")`, rangeRef)}},
		{{Value: "Failed", Formula: fmt.Sprintf(`COUNTIF(%s,"F")`, rangeRef)}},
		{{Value: "Not run", Formula: fmt.Sprintf(`COUNTIF(%s,"NY")`, rangeRef)}},
	}
}

type formulaCell struct{ Value, Formula string }

func renderSheet(headers []string, rows [][]string, formulas [][]formulaCell) string {
	var body strings.Builder
	body.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="15"/><sheetData>`)
	body.WriteString(`<row r="1">`)
	for column, value := range headers {
		body.WriteString(cellXML(column, 1, value, "1"))
	}
	body.WriteString(`</row>`)
	for rowIndex, values := range rows {
		rowNumber := rowIndex + 2
		fmt.Fprintf(&body, `<row r="%d">`, rowNumber)
		for column, value := range values {
			body.WriteString(cellXML(column, rowNumber, value, "2"))
		}
		body.WriteString(`</row>`)
	}
	for rowIndex, values := range formulas {
		rowNumber := rowIndex + 2
		fmt.Fprintf(&body, `<row r="%d">`, rowNumber)
		for column, value := range values {
			if column == 0 {
				body.WriteString(cellXML(0, rowNumber, value.Value, "2"))
			}
			if value.Formula != "" {
				fmt.Fprintf(&body, `<c r="B%d" s="2"><f>%s</f><v>0</v></c>`, rowNumber, xmlEscape(value.Formula))
			}
		}
		body.WriteString(`</row>`)
	}
	body.WriteString(`</sheetData><autoFilter ref="A1:` + columnName(len(headers)-1) + `1"/><pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/></worksheet>`)
	return body.String()
}

func cellXML(column, row int, value, style string) string {
	value = sanitizeCell(value)
	return fmt.Sprintf(`<c r="%s%d" t="inlineStr" s="%s"><is><t xml:space="preserve">%s</t></is></c>`, columnName(column), row, style, xmlEscape(value))
}

func sanitizeCell(value string) string {
	return sanitizeText(value, true)
}

func sanitizeText(value string, formulaSafe bool) string {
	var clean strings.Builder
	for _, r := range strings.ToValidUTF8(value, "�") {
		if r == '\t' || r == '\n' || r == '\r' || r >= 0x20 && r <= 0xD7FF || r >= 0xE000 && r <= 0xFFFD || r >= 0x10000 && r <= 0x10FFFF {
			clean.WriteRune(r)
		}
	}
	value = clean.String()
	if utf8.RuneCountInString(value) > maxExcelCellRunes {
		value = string([]rune(value)[:maxExcelCellRunes])
	}
	trimmed := strings.TrimLeft(value, " \t\r\n")
	if formulaSafe && trimmed != "" && strings.ContainsRune("=+-@", rune(trimmed[0])) {
		value = "'" + value
	}
	return value
}

func markdownText(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(sanitizeText(value, false), "|", `\|`), "\n", "<br>")
}

func xmlEscape(value string) string {
	var output strings.Builder
	_ = xml.EscapeText(&output, []byte(value))
	return output.String()
}

func columnName(index int) string {
	if index < 0 {
		return "A"
	}
	var name string
	for index >= 0 {
		name = string(rune('A'+index%26)) + name
		index = index/26 - 1
	}
	return name
}

const contentTypesXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet3.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet4.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>`
const rootRelationshipsXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`
const workbookXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Test Cases" sheetId="1" r:id="rId1"/><sheet name="Run History" sheetId="2" r:id="rId2"/><sheet name="Summary" sheetId="3" r:id="rId3"/><sheet name="Metadata" sheetId="4" r:id="rId4"/></sheets><calcPr calcId="0" fullCalcOnLoad="1"/></workbook>`
const workbookRelationshipsXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet3.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet4.xml"/><Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`
const stylesXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF1F4E78"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFill="1" applyFont="1" applyAlignment="1"><alignment wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><dxfs count="0"/><tableStyles count="0" defaultTableStyle="TableStyleMedium2" defaultPivotStyle="PivotStyleLight16"/></styleSheet>`
const corePropertiesXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:creator>%s</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">%s</dcterms:created></cp:coreProperties>`
const appPropertiesXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>AI Test Assistant</Application></Properties>`
